name: Actions

on:
  push:
  pull_request:
    types: [closed, opened, reopened, assigned]

jobs:

  actions:
    runs-on: ubuntu-latest
    needs: shell
    steps:
      - name: multiline script
        run: php --version
      - name: Varibles
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo "${{ github.token }}"
      - name: Greating
        id: greating
        uses: actions/hello-world-docker-action@v1
        with:
          who-to-greet: Misha Djachenko
      - name: Output of Greating
        run: echo "${{ steps.greating.outputs.time }}"
      - name: Before checkout
        run: |
          pwd
          ls -a
      - name: Checkout
        uses: actions/checkout@v2
      - name: After checkout
        run: |
          pwd
          ls -a

  php-tests:
    name: Php unit test
    runs-on: ubuntu-latest
    needs: actions
    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit

  deploy:
    name: Build and Deploy
    needs: php-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Setup Enviroment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
#      - name: Speed up the packages installation process
#        run: composer global require hirak/prestissimo
#      - name: Install Packages
#        run: composer install --no-dev
#      - name: Deploy to Server
#        uses: ngocquyhoang/deploy@laravel
#        with:
#          user: user
#          host: host
#          path: path
#          owner: owner
#        env:
#          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
